%% set data folder
cdslib = 'C:\Users\rhc307\data\cds-library';

trt_files = dir(fullfile(cdslib,'*TRT*'));
trt_names = vertcat({trt_files.name})';

trt_info_cell = cell(length(trt_names),6);

for i = 1:length(trt_names)
    trt_info_cell(i,:) = strsplit(trt_names{i},{'_','.'});
end

load_params = struct(...
    'array_name','S1',...
    'cont_signal_names',{{...
        'pos',...
	    'vel',...
	    'markers',...
	    'joint_ang',...
	    'joint_vel',...
	    'muscle_len',...
	    'muscle_vel',...
        }},...
    'event_names',{{...
        'startTime',...
        'endTime',...
        'goCueTime',...
        'bumpTime',...
        'targetStartTime',...
        'ctHoldTime',...
        'otHoldTime',...
        }},...
    'trial_meta',{{...
        'bumpDir',...
        'spaceNum',...
        }});

td_cell = cell(length(trt_names),1);
for i = 1:length(trt_names)
    td_cell{i} = loadTDfromCDS(fullfile(cdslib,trt_names{i}),load_params);
end

%%
savedir = 'C:\Users\rhc307\data\project-data\limblab\s1-kinematics\td-library';

trt_info = struct(...
    'monkey',trt_info_cell(:,1),...
    'date',trt_info_cell(:,2),...
    'filenum',trt_info_cell(:,5));

for i = [1,4:length(td_cell)]
    trial_data = td_cell{i};
    save(fullfile(savedir,sprintf('%s_%s_TRT_TD.mat',trt_info(i).monkey,trt_info(i).date)),'trial_data')
    fprintf('File %d saved\n',i)
end

%%
trial_data = horzcat(td_cell{2:3});
save(fullfile(savedir,sprintf('%s_%s_TRT_TD.mat',trt_info(2).monkey,trt_info(2).date)),'trial_data')