%% set data folder
cdslib = '/home/raeed/data/cds-library';

trt_files = dir(fullfile(cdslib,'*TRT*'));
trt_names = vertcat({trt_files.name})';

trt_info_cell = cell(length(trt_names),6);

for i = 1:length(trt_names)
    trt_info_cell(i,:) = strsplit(trt_names{i},{'_','.'});
end

trt_info = struct(...
    'monkey',trt_info_cell(:,1),...
    'date',trt_info_cell(:,2),...
    'filenum',trt_info_cell(:,5));

load_params = struct(...
    'array_name','S1',...
    'cont_signal_names',{{...
        'pos',...
	    'vel',...
	    'markers',...
	    'joint_ang',...
	    'joint_vel',...
	    'muscle_len',...
	    'muscle_vel',...
        }},...
    'event_names',{{...
        'startTime',...
        'endTime',...
        'goCueTime',...
        'bumpTime',...
        'targetStartTime',...
        'ctHoldTime',...
        'otHoldTime',...
        }},...
    'trial_meta',{{...
        'bumpDir',...
        'spaceNum',...
        }});

td_cell = cell(length(trt_info),1);
for i = 1:length(trt_info)
    td_cell{i} = loadTDfromCDS(fullfile(cdslib,trt_names{i}),load_params);
end
