%% set data folder
cdslib = 'C:\Users\rhc307\data\cds-library';

files = dir(fullfile(cdslib,'*RWDL*'));
namesDL = vertcat({files.name})';
files = dir(fullfile(cdslib,'*RWPM*'));
namesPM = vertcat({files.name})';

load_params_pm = struct(...
    'array_name','S1',...
    'cont_signal_names',{{...
        'pos',...
	    'vel',...
	    'markers',...
	    'joint_ang',...
	    'joint_vel',...
	    'muscle_len',...
	    'muscle_vel',...
        }},...
    'event_names',{{...
        'startTime',...
        'endTime',...
        'goCueTime',...
        }},...
    'meta',struct('spaceNum',1));

td_cell_pm = cell(length(namesPM),1);
for i = 1:length(namesPM)
    td_cell_pm{i} = loadTDfromCDS(fullfile(cdslib,namesPM{i}),load_params_pm);
    fprintf('File %d processed\n',i)
end

load_params_dl = struct(...
    'array_name','S1',...
    'cont_signal_names',{{...
        'pos',...
	    'vel',...
	    'markers',...
	    'joint_ang',...
	    'joint_vel',...
	    'muscle_len',...
	    'muscle_vel',...
        }},...
    'event_names',{{...
        'startTime',...
        'endTime',...
        'goCueTime',...
        }},...
    'meta',struct('spaceNum',2));
    
td_cell_dl = cell(length(namesDL),1);
for i = 1:length(namesDL)
    td_cell_dl{i} = loadTDfromCDS(fullfile(cdslib,namesDL{i}),load_params_dl);
    fprintf('File %d processed\n',i)
end

%%
savedir = 'C:\Users\rhc307\data\project-data\limblab\s1-kinematics\td-library';

file_info_cell = cell(length(namesPM),6);
for i = 1:length(namesPM)
    file_info_cell(i,:) = strsplit(namesPM{i},{'_','.'});
end
file_info_pm = struct(...
    'monkey',file_info_cell(:,1),...
    'date',file_info_cell(:,2),...
    'filenum',file_info_cell(:,5));

file_info_cell = cell(length(namesDL),6);
for i = 1:length(namesDL)
    file_info_cell(i,:) = strsplit(namesDL{i},{'_','.'});
end
file_info_dl = struct(...
    'monkey',file_info_cell(:,1),...
    'date',file_info_cell(:,2),...
    'filenum',file_info_cell(:,5));

assert(length(file_info_dl)==length(file_info_pm),'Different number of files...')
for i = 1:length(td_cell_pm)
    match = find(strcmpi(cat(1,{file_info_dl.monkey}),file_info_pm(i).monkey) & strcmpi(cat(1,{file_info_dl.date}),file_info_pm(i).date));
    assert(numel(match)==1,'Something is wrong with matching the files...')
    
    trial_data = horzcat(td_cell_pm{i},td_cell_dl{match});
    save(fullfile(savedir,sprintf('%s_%s_RWTW_TD.mat',file_info_pm(i).monkey,file_info_pm(i).date)),'trial_data')
    fprintf('File %d saved\n',i)
end
