function names = getEMGNames()
% function to return the names of EMGs

names = {...
    'BiMed',...
    'FCR',...
    'FCU',...
    'FDS',...
    'DeltAnt',...
    'DeltMid',...
    'DeltPos',...
    'Trap',...
    'Lat',...
    'TerMaj',...
    'InfSpin',...
    'TriMid',...
    'TriLat',...
    'TriMed',...
    'Brad',...
    'ECRb',...
    'ECU',...
    'EDC',...
    'PecSup',...
    'PecInf',...
    'Brach',...
    'BiLat',...
    };