function names = getJointNames()
% function to return the names of joints

names = {...
    'shoulder_adduction',...
    'shoulder_rotation',...
    'shoulder_flexion',...
    'elbow_flexion',...
    'radial_pronation',...
    'wrist_flexion',...
    'wrist_abduction',...
    };