function names = getMuscleNames()
% function to return the names of muscles

names = {...
    'abd_poll_longus',...
    'anconeus',...
    'bicep_lh',...
    'bicep_sh',...
    'brachialis',...
    'brachioradialis',...
    'coracobrachialis',...
    'deltoid_ant',...
    'deltoid_med',...
    'deltoid_pos',...
    'dorsoepitrochlearis',...
    'ext_carpi_rad_longus',...
    'ext_carp_rad_brevis',...
    'ext_carpi_ulnaris',...
    'ext_digitorum',...
    'ext_digiti',...
    'ext_indicis',...
    'flex_carpi_radialis',...
    'flex_carpi_ulnaris',...
    'flex_digit_profundus',...
    'flex_digit_superficialis',...
    'flex_poll_longus',...
    'infraspinatus',...
    'lat_dorsi_sup',...
    'lat_dorsi_cen',...
    'lat_dorsi_inf',...
    'palmaris_longus',...
    'pectoralis_sup',...
    'pectoralis_inf',...
    'pronator_quad',...
    'pronator_teres',...
    'subscapularis',...
    'supinator',...
    'supraspinatus',...
    'teres_major',...
    'teres_minor',...
    'tricep_lat',...
    'tricep_lon',...
    'tricep_sho',...
    };
