function names = getMuscleNames()
% function to return the names of muscles

names = {...
    't'
    'abd_poll_longus_len'
    'anconeus_len'
    'bicep_lh_len'
    'bicep_sh_len'
    'brachialis_len'
    'brachioradialis_len'
    'coracobrachialis_len'
    'deltoid_ant_len'
    'deltoid_med_len'
    'deltoid_pos_len'
    'dorsoepitrochlearis_len'
    'ext_carpi_rad_longus_len'
    'ext_carp_rad_brevis_len'
    'ext_carpi_ulnaris_len'
    'ext_digitorum_len'
    'ext_digiti_len'
    'ext_indicis_len'
    'flex_carpi_radialis_len'
    'flex_carpi_ulnaris_len'
    'flex_digit_profundus_len'
    'flex_digit_superficialis_len'
    'flex_poll_longus_len'
    'infraspinatus_len'
    'lat_dorsi_sup_len'
    'lat_dorsi_cen_len'
    'lat_dorsi_inf_len'
    'palmaris_longus_len'
    'pectoralis_sup_len'
    'pectoralis_inf_len'
    'pronator_quad_len'
    'pronator_teres_len'
    'subscapularis_len'
    'supinator_len'
    'supraspinatus_len'
    'teres_major_len'
    'teres_minor_len'
    'tricep_lat_len'
    'tricep_lon_len'
    'tricep_sho_len'
    };