function names = getMarkerNames()
% function to return the names of markers, as they appear in raw cds format

temp = {...
    'Marker_1',...
    'Marker_2',...
    'Marker_3',...
    'Marker_4',...
    'Marker_5',...
    'Marker_6',...
    'Marker_7',...
    'Marker_8',...
    'Shoulder_JC',...
    'Pronation_Pt1',...
    };
names = cell(1,3*length(temp));

for i = 1:length(temp)
    names(((i-1)*3+1):(i*3)) = strcat(temp(i),{'_y','_z','_x'});
end